runtime: python39
handlers:
  - url: /(.*\.(html|css|js|png|jpg|gif|svg|ico|txt))$
    static_files: \1
    upload: .*\.(html|css|js|png|jpg|gif|svg|ico|txt)$
    expiration: "1h"
  - url: /.*
    static_files: index.html
    upload: index.html
    mime_type: text/html
    expiration: "1h"
